### ISSUE TITLE
Visualization and Understanding the data

### ISSUE THREAD

**Issue by akshaybahadur21** [harish988/AVENGERS#2]
@harish988 @Vivek0712 
Now that we have the dataset ready, we need to visualize and understand it.
This is important because, 

- Help us understand the requirement of more data
- Whether the classes are imbalance

How should this be done,

- A good starting point will be [Dipanjan's repo](https://github.com/dipanjanS/art_of_data_visualization)
- You should explore more over the internet.

The end goal is to make even a normal person realize the patterns in data and that could be achieved effective visualization.

**Comment by harish988** [comment]
@akshaybahadur21 
Hi. Sorry for the delay. We have been busy on the Build for Digital India boot camp. 
The data visualizations have been done and can be found at https://github.com/harish988/AVENGERS/blob/master/Dataset/Visualisation.ipynb.

I know that we are behind the schedule. So I have added the other two members of the team as collaborators - @anamalaii and @HariharanShanmugam. You can split the tasks between four of us so that we could wrap up the project soon.
